server:
  name: "amusing-x/europa"
  http_server:
    addr: :10001
  grpc_server:
    network: tcp
    address: :20001
grpc_client:
  callisto:
    addr: localhost:20002
  user:
    addr: localhost:20005
  charon:
    addr: localhost:20004
mysql:
  europadb:
    db: europadb
    user: test111
    password: pass123456
    host: localhost
    port: 3306
    protocol: tcp
    max_life_time: 3600
    max_open_conns: 100
    max_idle_conns: 10
oauth:
  github:
    provider: "GitHub"
    client_id: ""
    client_secrets: ""
    redirect_url: ""
redis:
  redis1:
    addr: 127.0.0.1:6379
    db_no: 1
session_store:
  redis:
    addr: 127.0.0.1:6379
    db_no: 2
