// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.8.0
// source: pangu/proto/attribute_list.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttributeListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query         string  `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int64   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          string  `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Filter        string  `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	Offset        int64   `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	Ids           []int64 `protobuf:"varint,8,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	SubProductIds []int64 `protobuf:"varint,9,rep,packed,name=subProductIds,proto3" json:"subProductIds,omitempty"`
}

func (x *AttributeListRequest) Reset() {
	*x = AttributeListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pangu_proto_attribute_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeListRequest) ProtoMessage() {}

func (x *AttributeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pangu_proto_attribute_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeListRequest.ProtoReflect.Descriptor instead.
func (*AttributeListRequest) Descriptor() ([]byte, []int) {
	return file_pangu_proto_attribute_list_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeListRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AttributeListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AttributeListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AttributeListRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *AttributeListRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *AttributeListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AttributeListRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *AttributeListRequest) GetSubProductIds() []int64 {
	if x != nil {
		return x.SubProductIds
	}
	return nil
}

type AttributeListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int64        `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit   int64        `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total   int64        `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	HasNext bool         `protobuf:"varint,4,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	Data    []*Attribute `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AttributeListResponse) Reset() {
	*x = AttributeListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pangu_proto_attribute_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeListResponse) ProtoMessage() {}

func (x *AttributeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pangu_proto_attribute_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeListResponse.ProtoReflect.Descriptor instead.
func (*AttributeListResponse) Descriptor() ([]byte, []int) {
	return file_pangu_proto_attribute_list_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeListResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AttributeListResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AttributeListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AttributeListResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *AttributeListResponse) GetData() []*Attribute {
	if x != nil {
		return x.Data
	}
	return nil
}

type AttributeWithSubProductListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*AttributeWithSubProduct `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AttributeWithSubProductListResponse) Reset() {
	*x = AttributeWithSubProductListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pangu_proto_attribute_list_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeWithSubProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeWithSubProductListResponse) ProtoMessage() {}

func (x *AttributeWithSubProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pangu_proto_attribute_list_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeWithSubProductListResponse.ProtoReflect.Descriptor instead.
func (*AttributeWithSubProductListResponse) Descriptor() ([]byte, []int) {
	return file_pangu_proto_attribute_list_proto_rawDescGZIP(), []int{2}
}

func (x *AttributeWithSubProductListResponse) GetData() []*AttributeWithSubProduct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pangu_proto_attribute_list_proto protoreflect.FileDescriptor

var file_pangu_proto_attribute_list_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x1a, 0x1b, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x01,
	0x0a, 0x14, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64,
	0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x24, 0x0a, 0x0d,
	0x73, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x73, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49,
	0x64, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x15, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68,
	0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x60, 0x0a, 0x23, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x53, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x61, 0x6e, 0x67, 0x75,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x38, 0x5a, 0x36, 0x61, 0x6d, 0x75, 0x73, 0x69, 0x6e, 0x67,
	0x78, 0x2e, 0x66, 0x69, 0x74, 0x2f, 0x61, 0x6d, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x78, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pangu_proto_attribute_list_proto_rawDescOnce sync.Once
	file_pangu_proto_attribute_list_proto_rawDescData = file_pangu_proto_attribute_list_proto_rawDesc
)

func file_pangu_proto_attribute_list_proto_rawDescGZIP() []byte {
	file_pangu_proto_attribute_list_proto_rawDescOnce.Do(func() {
		file_pangu_proto_attribute_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_pangu_proto_attribute_list_proto_rawDescData)
	})
	return file_pangu_proto_attribute_list_proto_rawDescData
}

var file_pangu_proto_attribute_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pangu_proto_attribute_list_proto_goTypes = []interface{}{
	(*AttributeListRequest)(nil),                // 0: panguservice.AttributeListRequest
	(*AttributeListResponse)(nil),               // 1: panguservice.AttributeListResponse
	(*AttributeWithSubProductListResponse)(nil), // 2: panguservice.AttributeWithSubProductListResponse
	(*Attribute)(nil),                           // 3: panguservice.Attribute
	(*AttributeWithSubProduct)(nil),             // 4: panguservice.AttributeWithSubProduct
}
var file_pangu_proto_attribute_list_proto_depIdxs = []int32{
	3, // 0: panguservice.AttributeListResponse.data:type_name -> panguservice.Attribute
	4, // 1: panguservice.AttributeWithSubProductListResponse.data:type_name -> panguservice.AttributeWithSubProduct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pangu_proto_attribute_list_proto_init() }
func file_pangu_proto_attribute_list_proto_init() {
	if File_pangu_proto_attribute_list_proto != nil {
		return
	}
	file_pangu_proto_attribute_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pangu_proto_attribute_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pangu_proto_attribute_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pangu_proto_attribute_list_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeWithSubProductListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pangu_proto_attribute_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pangu_proto_attribute_list_proto_goTypes,
		DependencyIndexes: file_pangu_proto_attribute_list_proto_depIdxs,
		MessageInfos:      file_pangu_proto_attribute_list_proto_msgTypes,
	}.Build()
	File_pangu_proto_attribute_list_proto = out.File
	file_pangu_proto_attribute_list_proto_rawDesc = nil
	file_pangu_proto_attribute_list_proto_goTypes = nil
	file_pangu_proto_attribute_list_proto_depIdxs = nil
}
