// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.8.0
// source: pangu/proto/attribute_mapping_list.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttributeMappingListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query  string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page   int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit  int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort   string `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Filter string `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *AttributeMappingListRequest) Reset() {
	*x = AttributeMappingListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pangu_proto_attribute_mapping_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeMappingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeMappingListRequest) ProtoMessage() {}

func (x *AttributeMappingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pangu_proto_attribute_mapping_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeMappingListRequest.ProtoReflect.Descriptor instead.
func (*AttributeMappingListRequest) Descriptor() ([]byte, []int) {
	return file_pangu_proto_attribute_mapping_list_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeMappingListRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AttributeMappingListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AttributeMappingListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AttributeMappingListRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *AttributeMappingListRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type AttributeMappingListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int64               `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit   int64               `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total   int64               `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	HasNext bool                `protobuf:"varint,4,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	Data    []*AttributeMapping `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AttributeMappingListResponse) Reset() {
	*x = AttributeMappingListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pangu_proto_attribute_mapping_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeMappingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeMappingListResponse) ProtoMessage() {}

func (x *AttributeMappingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pangu_proto_attribute_mapping_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeMappingListResponse.ProtoReflect.Descriptor instead.
func (*AttributeMappingListResponse) Descriptor() ([]byte, []int) {
	return file_pangu_proto_attribute_mapping_list_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeMappingListResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AttributeMappingListResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AttributeMappingListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AttributeMappingListResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *AttributeMappingListResponse) GetData() []*AttributeMapping {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pangu_proto_attribute_mapping_list_proto protoreflect.FileDescriptor

var file_pangu_proto_attribute_mapping_list_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x61, 0x6e, 0x67,
	0x75, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x23, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f,
	0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01,
	0x0a, 0x1b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xac, 0x01, 0x0a, 0x1c, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61,
	0x73, 0x4e, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73,
	0x4e, 0x65, 0x78, 0x74, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x38, 0x5a, 0x36, 0x61, 0x6d, 0x75, 0x73,
	0x69, 0x6e, 0x67, 0x78, 0x2e, 0x66, 0x69, 0x74, 0x2f, 0x61, 0x6d, 0x75, 0x73, 0x69, 0x6e, 0x67,
	0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x61, 0x6e, 0x67, 0x75, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pangu_proto_attribute_mapping_list_proto_rawDescOnce sync.Once
	file_pangu_proto_attribute_mapping_list_proto_rawDescData = file_pangu_proto_attribute_mapping_list_proto_rawDesc
)

func file_pangu_proto_attribute_mapping_list_proto_rawDescGZIP() []byte {
	file_pangu_proto_attribute_mapping_list_proto_rawDescOnce.Do(func() {
		file_pangu_proto_attribute_mapping_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_pangu_proto_attribute_mapping_list_proto_rawDescData)
	})
	return file_pangu_proto_attribute_mapping_list_proto_rawDescData
}

var file_pangu_proto_attribute_mapping_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pangu_proto_attribute_mapping_list_proto_goTypes = []interface{}{
	(*AttributeMappingListRequest)(nil),  // 0: panguservice.AttributeMappingListRequest
	(*AttributeMappingListResponse)(nil), // 1: panguservice.AttributeMappingListResponse
	(*AttributeMapping)(nil),             // 2: panguservice.AttributeMapping
}
var file_pangu_proto_attribute_mapping_list_proto_depIdxs = []int32{
	2, // 0: panguservice.AttributeMappingListResponse.data:type_name -> panguservice.AttributeMapping
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pangu_proto_attribute_mapping_list_proto_init() }
func file_pangu_proto_attribute_mapping_list_proto_init() {
	if File_pangu_proto_attribute_mapping_list_proto != nil {
		return
	}
	file_pangu_proto_attribute_mapping_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pangu_proto_attribute_mapping_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeMappingListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pangu_proto_attribute_mapping_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeMappingListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pangu_proto_attribute_mapping_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pangu_proto_attribute_mapping_list_proto_goTypes,
		DependencyIndexes: file_pangu_proto_attribute_mapping_list_proto_depIdxs,
		MessageInfos:      file_pangu_proto_attribute_mapping_list_proto_msgTypes,
	}.Build()
	File_pangu_proto_attribute_mapping_list_proto = out.File
	file_pangu_proto_attribute_mapping_list_proto_rawDesc = nil
	file_pangu_proto_attribute_mapping_list_proto_goTypes = nil
	file_pangu_proto_attribute_mapping_list_proto_depIdxs = nil
}
