// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package userservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AmusingxUserServiceClient is the client API for AmusingxUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AmusingxUserServiceClient interface {
	Pong(ctx context.Context, in *BlankParams, opts ...grpc.CallOption) (*PongResponse, error)
}

type amusingxUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAmusingxUserServiceClient(cc grpc.ClientConnInterface) AmusingxUserServiceClient {
	return &amusingxUserServiceClient{cc}
}

func (c *amusingxUserServiceClient) Pong(ctx context.Context, in *BlankParams, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, "/userservice.AmusingxUserService/Pong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AmusingxUserServiceServer is the server API for AmusingxUserService service.
// All implementations must embed UnimplementedAmusingxUserServiceServer
// for forward compatibility
type AmusingxUserServiceServer interface {
	Pong(context.Context, *BlankParams) (*PongResponse, error)
	mustEmbedUnimplementedAmusingxUserServiceServer()
}

// UnimplementedAmusingxUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAmusingxUserServiceServer struct {
}

func (*UnimplementedAmusingxUserServiceServer) Pong(context.Context, *BlankParams) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pong not implemented")
}
func (*UnimplementedAmusingxUserServiceServer) mustEmbedUnimplementedAmusingxUserServiceServer() {}

func RegisterAmusingxUserServiceServer(s *grpc.Server, srv AmusingxUserServiceServer) {
	s.RegisterService(&_AmusingxUserService_serviceDesc, srv)
}

func _AmusingxUserService_Pong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlankParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmusingxUserServiceServer).Pong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userservice.AmusingxUserService/Pong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmusingxUserServiceServer).Pong(ctx, req.(*BlankParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _AmusingxUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userservice.AmusingxUserService",
	HandlerType: (*AmusingxUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pong",
			Handler:    _AmusingxUserService_Pong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
