server:
  name: "amusing-x/pluto"
  http_server:
    addr: :10003
  grpc_server:
    network: tcp
    address: :20003
mysql:
  plutodb:
    db: plutodb
    user: test111
    password: pass123456
    host: localhost
    port: 3306
    protocol: tcp
    max_life_time: 3600
    max_open_conns: 100
    max_idle_conns: 10
redis:
  redis1:
    addr: 127.0.0.1:6379
    db_no: 1