// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.8.0
// source: category_list.proto

package panguservice

import "github.com/ItsWewin/superfactory/aerror"

func (r *CategoryListRequest) Valid() aerror.Error {
	if r.Page < 1 {
		r.Page = 1
	}

	if r.Limit < 1 {
		r.Limit = 20
	}

	return nil
}
