// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package panguservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PanGuServiceClient is the client API for PanGuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PanGuServiceClient interface {
	Pong(ctx context.Context, in *BlankParams, opts ...grpc.CallOption) (*PongResponse, error)
	CategoryCreate(ctx context.Context, in *CategoryCreateRequest, opts ...grpc.CallOption) (*CategoryCreateResponse, error)
	CategoryList(ctx context.Context, in *CategoryListRequest, opts ...grpc.CallOption) (*CategoryListResponse, error)
}

type panGuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPanGuServiceClient(cc grpc.ClientConnInterface) PanGuServiceClient {
	return &panGuServiceClient{cc}
}

func (c *panGuServiceClient) Pong(ctx context.Context, in *BlankParams, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, "/panguservice.PanGuService/Pong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *panGuServiceClient) CategoryCreate(ctx context.Context, in *CategoryCreateRequest, opts ...grpc.CallOption) (*CategoryCreateResponse, error) {
	out := new(CategoryCreateResponse)
	err := c.cc.Invoke(ctx, "/panguservice.PanGuService/CategoryCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *panGuServiceClient) CategoryList(ctx context.Context, in *CategoryListRequest, opts ...grpc.CallOption) (*CategoryListResponse, error) {
	out := new(CategoryListResponse)
	err := c.cc.Invoke(ctx, "/panguservice.PanGuService/CategoryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PanGuServiceServer is the server API for PanGuService service.
// All implementations must embed UnimplementedPanGuServiceServer
// for forward compatibility
type PanGuServiceServer interface {
	Pong(context.Context, *BlankParams) (*PongResponse, error)
	CategoryCreate(context.Context, *CategoryCreateRequest) (*CategoryCreateResponse, error)
	CategoryList(context.Context, *CategoryListRequest) (*CategoryListResponse, error)
	mustEmbedUnimplementedPanGuServiceServer()
}

// UnimplementedPanGuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPanGuServiceServer struct {
}

func (UnimplementedPanGuServiceServer) Pong(context.Context, *BlankParams) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pong not implemented")
}
func (UnimplementedPanGuServiceServer) CategoryCreate(context.Context, *CategoryCreateRequest) (*CategoryCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategoryCreate not implemented")
}
func (UnimplementedPanGuServiceServer) CategoryList(context.Context, *CategoryListRequest) (*CategoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategoryList not implemented")
}
func (UnimplementedPanGuServiceServer) mustEmbedUnimplementedPanGuServiceServer() {}

// UnsafePanGuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PanGuServiceServer will
// result in compilation errors.
type UnsafePanGuServiceServer interface {
	mustEmbedUnimplementedPanGuServiceServer()
}

func RegisterPanGuServiceServer(s grpc.ServiceRegistrar, srv PanGuServiceServer) {
	s.RegisterService(&PanGuService_ServiceDesc, srv)
}

func _PanGuService_Pong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlankParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanGuServiceServer).Pong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/panguservice.PanGuService/Pong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanGuServiceServer).Pong(ctx, req.(*BlankParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _PanGuService_CategoryCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanGuServiceServer).CategoryCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/panguservice.PanGuService/CategoryCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanGuServiceServer).CategoryCreate(ctx, req.(*CategoryCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PanGuService_CategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanGuServiceServer).CategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/panguservice.PanGuService/CategoryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanGuServiceServer).CategoryList(ctx, req.(*CategoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PanGuService_ServiceDesc is the grpc.ServiceDesc for PanGuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PanGuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panguservice.PanGuService",
	HandlerType: (*PanGuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pong",
			Handler:    _PanGuService_Pong_Handler,
		},
		{
			MethodName: "CategoryCreate",
			Handler:    _PanGuService_CategoryCreate_Handler,
		},
		{
			MethodName: "CategoryList",
			Handler:    _PanGuService_CategoryList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "my_rpc_service_1639662246094730000.proto",
}
