server:
  name: amusing-x/user
  http_server:
    addr: :10005
  grpc_server:
    network: tcp
    address: :20005
grpc_client:
  callisto:
    addr: 20002
mysql:
  user:
    db: ganymededb
    user: test111
    password: pass123456
    host: localhost
    port: 3306
    protocol: tcp
    max_life_time: 3600
    max_open_conns: 100
    max_idle_conns: 10
oauth:
  store:
    prefix: oauth:prefix
    max_life_time: 600
    redis:
      addr: 127.0.0.1:6379
      db_no: 4
  github:
    for_amusing_x:
      provider: github
      client_id: 829182a40c33d7e560a8
      client_secrets: f19a51b5d93d13a2ec431e4b959f0ca5e81834de
      redirect_url: http://localhost:3000/login/oauth
      access_token_url: https://github.com/login/oauth/access_token
      user_profile_url: https://api.github.com/user
      oauth_url: https://github.com/login/oauth/authorize
      scope: user
      client_server: amusingx
    for_pan_gu:
      provider: github
      client_id: bc4c3ec67a6c3116bfe0
      client_secrets: 7c46a61911dcb30d7e8e60e7c9597de938c44cd5
      redirect_url: http://localhost:5000/login/oauth
      access_token_url: https://github.com/login/oauth/access_token
      user_profile_url: https://api.github.com/user
      oauth_url: https://github.com/login/oauth/authorize
      scope: user
      client_server: pangu
  wechat:
    provider: wechat
    client_id: 829182a40c33d7e560a8
    client_secrets: f19a51b5d93d13a2ec431e4b959f0ca5e81834de
    redirect_url: http://localhost:3000/login/oauth
    access_token_url: https://github.com/login/oauth/access_token
    user_profile_url: https://api.github.com/user
redis:
  redis1:
    addr: 127.0.0.1:6379
    db_no: 1
session_store:
  prefix: "sid2"
  redis:
    addr: 127.0.0.1:6379
    db_no: 2